---
name: asyngrep
description: async grep.
---

=pod

=head1 dps-asyngrep

Denops Async Grep plugin.

=head1 Features X<asyngrep-features>

This plugin is a wrapper for some grep tools.

L<非同期に Grep 検索する (denops.vim)|https://zenn.dev/yukimemi/articles/2021-03-21-dps-asyngrep>

[![asciicast](https://asciinema.org/a/JFQPdITg4is48RwQLpcTLTIJv.svg)](https://asciinema.org/a/JFQPdITg4is48RwQLpcTLTIJv)


=head1 Installation X<asyngrep-installation>

If you use L<folke/lazy.nvim|https://github.com/folke/lazy.nvim>.

=begin lua

{
  "yukimemi/dps-asyngrep",
  lazy = false,
  dependencies = {
    "vim-denops/denops.vim",
  },
}

=end lua

If you use L<yukimemi/dvpm|https://github.com/yukimemi/dvpm>.

=begin typescript

dvpm.add({ url: "yukimemi/dps-asyngrep" });

=end typescript

=head1 Requirements X<asyngrep-requirements>

=item [Deno - A modern runtime for JavaScript and TypeScript](https://deno.land/)

=item [vim-denops/denops.vim: 🐜 An ecosystem of Vim/Neovim which allows developers to write cross-platform plugins in Deno](https://github.com/vim-denops/denops.vim)

=item Some grep tools. rg, pt, jvgrep, etc.

=head1 Usage X<asyngrep-usage>

No special settings are required.
Default is L<config.toml|https://github.com/yukimemi/dps-asyngrep/blob/main/denops/asyngrep/config.toml>

=head1 Commands X<asyngrep-commands>

C<:Agp>                                                                X<:Agp>
Asyncronous grep.

=head1 Config X<asyngrep-config>

No settings are required. However, the following settings can be made if necessary.

C<g:asyngrep_debug>                        X<g:asyngrep_debug>
Enable debug messages.
default is v:false

C<g:asyngrep_cfg_path>                                          X<g:asyngrep_cfg_path>
Path to config toml file path.
default is `~/.asyngrep.toml`

=head1 Example X<asyngrep-example>

=head2 Example vim settings.

=begin vim

" Debug log option.
let g:asyngrep_debug = v:false
" User config (not necessary)
let g:asyngrep_cfg_path = "~/.config/asyngrep/config.toml"

" Grep with default tool.
nnoremap <space>ss <cmd>Agp<cr>

" Grep with ripgrep.
nnoremap <space>sr <cmd>Agp --tool=ripgrep<cr>
" Grep with pt.
nnoremap <space>sp <cmd>Agp --tool=pt<cr>
" Grep with jvgrep.
nnoremap <space>sj <cmd>Agp --tool=jvgrep<cr>

=end vim

=head2 Example toml config.

=begin toml

[[tool]]
name = "ripgrep-all"
cmd = "rg"
arg = ["-i", "--vimgrep", "--no-heading", "--hidden", "--no-ignore", "--regexp"]
# Agp --tool=ripgrep-all

[[tool]]
name = "jvgrep-all"
cmd = "jvgrep"
arg = ["-i", "--no-color", "-I", "-R", "-8"]
# Agp --tool=jvgrep-all

[[tool]]
name = "pt-all"
cmd = "pt"
arg = ["-i", "--nogroup", "--nocolor", "--smart-case", "--skip-vcs-ignores", "--hidden"]
# Agp --tool=pt-all

[[tool]]
name = "default"
cmd = "pt"
arg = ["-i", "--nogroup", "--nocolor"]
# Agp

=end toml

=head1 License X<asyngrep-license>

Licensed under MIT License.

Copyright (c) 2023 yukimemi

=cut
